eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:pwd@localhost:8761/eureka/

server:
  port: 8070

spring:
  application:
    name: platform-user
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://192.168.31.171:3306/jtm?autoReconnect=true&characterEncoding=UTF-8&serverTimezone=Hongkong
    data-password: 123456
    data-username: root