server:
  port: 38080

spring:
  application:
    name: monitor-spring-boot-admin
  security:
    user:
      name: admin
      password: pwd
  boot:
    admin:
      client:
        api-path: http://localhost:38080

logging:
  level:
    org:
      springframework:
        security: DEBUG

eureka:
  instance:
    hostname: localhost
    health-check-url: /actuator/health
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://admin:pwd@localhost:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enable-self-preservation: false

management:
  endpoints:
    jmx:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
