eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:pwd@localhost:8761/eureka/

server:
  port: 28080

spring:
  application:
    name: gateway-server
  boot:
    admin:
      client:
        url: http://localhost:38080
management:
  endpoints:
    jmx:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
